### ISSUE TITLE
Improvement: Send received message from one client to all other connected clients

### ISSUE THREAD

**Issue by mp84** [DJONvl/iobroker.mysensors#7]
Hi,

is it possible to implement (maybe optional in config) the function to process a received message by a client to other connected clients? At the moment it seems like each connection from a client to the controller is isolated to each other.

e.g.: Message from Client 1 is seen by the controller (ioBroker) but not by Client 2.

Usecase for this feature would be a second Client (eg MyController) for OTA Updating Sensor nodes.
This makes it neccesary that the second client can communicate with nodes throug first client (the Gateway)

**Comment by maxtox** [comment]
Please write this issue (auch in Deutsch wenn du wills) in ioBroker Forum, because DEV of ioBroker is bluefox and not DJONvl...


Me and bluefox are reading all of the issues there.

You can create a pull request (even with including of OTA)

Thank you!
